"""desc

Revision ID: 0daff59c8ea1
Revises: 1f99c3343a65
Create Date: 2023-07-29 12:53:54.760913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0daff59c8ea1'
down_revision = '1f99c3343a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faculty', 'description')
    # ### end Alembic commands ###
