"""univ

Revision ID: 13362fdb3510
Revises: 560dbe910294
Create Date: 2023-07-29 05:26:28.794408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13362fdb3510'
down_revision = '560dbe910294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('lat', sa.String(), nullable=True))
    op.add_column('university', sa.Column('lon', sa.String(), nullable=True))
    op.add_column('university', sa.Column('address', sa.String(), nullable=True))
    op.add_column('university', sa.Column('photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'photo')
    op.drop_column('university', 'address')
    op.drop_column('university', 'lon')
    op.drop_column('university', 'lat')
    # ### end Alembic commands ###
