"""aa

Revision ID: e0e881d0fbb1
Revises: 0daff59c8ea1
Create Date: 2023-07-29 15:11:11.602711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e881d0fbb1'
down_revision = '0daff59c8ea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userfield',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userfield_field_id'), 'userfield', ['field_id'], unique=False)
    op.create_index(op.f('ix_userfield_id'), 'userfield', ['id'], unique=False)
    op.create_index(op.f('ix_userfield_user_id'), 'userfield', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userfield_user_id'), table_name='userfield')
    op.drop_index(op.f('ix_userfield_id'), table_name='userfield')
    op.drop_index(op.f('ix_userfield_field_id'), table_name='userfield')
    op.drop_table('userfield')
    # ### end Alembic commands ###
