"""s

Revision ID: e0fc7f648ae0
Revises: e3d49e0603d6
Create Date: 2023-07-29 17:11:40.468359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0fc7f648ae0'
down_revision = 'e3d49e0603d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support', sa.Column('title', sa.String(), nullable=True))
    op.add_column('support', sa.Column('lesson_count', sa.Integer(), nullable=True))
    op.add_column('support', sa.Column('task_count', sa.Integer(), nullable=True))
    op.add_column('support', sa.Column('description', sa.String(), nullable=True))
    op.add_column('support', sa.Column('content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support', 'content')
    op.drop_column('support', 'description')
    op.drop_column('support', 'task_count')
    op.drop_column('support', 'lesson_count')
    op.drop_column('support', 'title')
    # ### end Alembic commands ###
