"""field__

Revision ID: e89082d8cb86
Revises: 24491c7fc2c1
Create Date: 2023-07-29 06:54:57.212960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89082d8cb86'
down_revision = '24491c7fc2c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field', sa.Column('url', sa.String(), nullable=True))
    op.add_column('field', sa.Column('description', sa.String(), nullable=True))
    op.add_column('field', sa.Column('min_mark', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_field_min_mark'), 'field', ['min_mark'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_field_min_mark'), table_name='field')
    op.drop_column('field', 'min_mark')
    op.drop_column('field', 'description')
    op.drop_column('field', 'url')
    # ### end Alembic commands ###
